apiVersion: v1
kind: ConfigMap
metadata:
  name: trafficgreen-config
  namespace: kube-system
data:
  PROM_URL: "http://prometheus-server.monitoring.svc:9090"
  QUERY: "sum(rate(nginx_ingress_controller_requests[1m]))"
  THRESHOLD: "1"
  IDLE_GRACE: "300"
  CHECK_INTERVAL: "30"
