apiVersion: apps/v1
kind: Deployment
metadata:
  name: wake-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wake-listener
  template:
    metadata:
      labels:
        app: wake-listener
    spec:
      containers:
        - name: wake-listener
          image: imksprateek/incoming-traffic-listener:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wake-listener
spec:
  selector:
    app: wake-listener
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
